version: '3.7'
services:
  pulse:
    image: pulse
    build: .
    volumes:
      - type: bind
        source: ./gifs
        target: /tmp/gifs
      - type: bind
        source: ./maps
        target: /tmp/maps
